function dlcdataread2 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BEHAVIORDLCRESNET50GRCCFMAR16SHUFFLE112000 = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the numeric data.
%
%  BEHAVIORDLCRESNET50GRCCFMAR16SHUFFLE112000 = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  behaviorDLCresnet50GrcCfMar16shuffle112000 = importfile("Z:\Interval-Img\Imaging\21049-1\022723\behaviorDLC_resnet50_Grc-CfMar16shuffle1_12000.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Mar-2023 14:41:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "DLC_resnet50_GrcCfMar16shuffle1_12000", "DLC_resnet50_GrcCfMar16shuffle1_12000_1", "Var4", "DLC_resnet50_GrcCfMar16shuffle1_12000_3", "DLC_resnet50_GrcCfMar16shuffle1_12000_4", "Var7", "DLC_resnet50_GrcCfMar16shuffle1_12000_6", "DLC_resnet50_GrcCfMar16shuffle1_12000_7", "Var10", "DLC_resnet50_GrcCfMar16shuffle1_12000_9", "DLC_resnet50_GrcCfMar16shuffle1_12000_10", "Var13", "DLC_resnet50_GrcCfMar16shuffle1_12000_12", "DLC_resnet50_GrcCfMar16shuffle1_12000_13", "Var16"];
opts.SelectedVariableNames = ["DLC_resnet50_GrcCfMar16shuffle1_12000", "DLC_resnet50_GrcCfMar16shuffle1_12000_1", "DLC_resnet50_GrcCfMar16shuffle1_12000_3", "DLC_resnet50_GrcCfMar16shuffle1_12000_4", "DLC_resnet50_GrcCfMar16shuffle1_12000_6", "DLC_resnet50_GrcCfMar16shuffle1_12000_7", "DLC_resnet50_GrcCfMar16shuffle1_12000_9", "DLC_resnet50_GrcCfMar16shuffle1_12000_10", "DLC_resnet50_GrcCfMar16shuffle1_12000_12", "DLC_resnet50_GrcCfMar16shuffle1_12000_13"];
opts.VariableTypes = ["string", "double", "double", "string", "double", "double", "string", "double", "double", "string", "double", "double", "string", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var4", "Var7", "Var10", "Var13", "Var16"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var4", "Var7", "Var10", "Var13", "Var16"], "EmptyFieldRule", "auto");

% Import the data
dlcdataread2 = readtable(filename, opts);

%% Convert to output type
dlcdataread2 = table2array(dlcdataread2);
end